import mongoose from 'mongoose';

// ── InsightCache ───────────────────────────────────────────────────────────────
// Stores AI-generated insights per org so they survive page reloads.
// One document per org — replaced on every refresh (billing fetch or midnight cron).
//
// Lifecycle:
//   • Created / updated when /api/aws/billing is called
//   • Deleted and recreated every day at 00:00 (midnight cron job)
//   • Read by GET /api/dashboard/insights — no Groq call at read time

const insightCacheSchema = new mongoose.Schema(
  {
    orgId: {
      type: String,
      required: true,
      unique: true, // One cache doc per org
      index: true,
    },

    // ISO date string of the day these insights represent (YYYY-MM-DD)
    // Used by the cron job to detect stale caches (yesterday's date)
    dateKey: { type: String, required: true }, // e.g. "2026-05-03"

    // When these insights were last generated by Groq
    generatedAt: { type: Date, default: Date.now },

    // The billing snapshot's fetchedAt at the time of generation
    // Lets us detect if billing data has changed since last generation
    billingFetchedAt: { type: Date, default: null },

    // The fully normalised insight objects (same shape as frontend expects)
    insights: { type: mongoose.Schema.Types.Mixed, default: [] },

    // Top-level billing summary at time of generation (for SummaryBar)
    summary: { type: mongoose.Schema.Types.Mixed, default: {} },
  },
  { timestamps: false },
);

const InsightCache = mongoose.model('InsightCache', insightCacheSchema);
export default InsightCache;
